const mongoose=require("mongoose");
const userSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true,
        trim:true
    },
    username:{
        type:String,
        required:true,
        unique:true,
        trim:true,
        lowercase:true
    },
    email:{
        type:String,
        required:true,
        unique:true,
        trim:true,
        lowercase:true
    },
    password:{
        type:String,
        required:true,
    },
    codeforcesHandles:[{
        handle:{
            type:String,
            required:true,
            trim:true,
        },
        isOwn:{
            type:Boolean,
            default:false
        }
    }]
},
{
    timestamps:true
}
);
const User=mongoose.model("User",userSchema);
module.exports=User;
