const express=require("express");
const { getHealth } = require("../controllers/healthController");
const { getUser, getRatingHistory, getSubmission, getanalytics } = require("../controllers/userController");
const router=express.Router();
router.get("/",getHealth);
router.get("/users/:handle",getUser);
router.get("/users/:handle/rating",getRatingHistory);
router.get("/users/:handle/submission",getSubmission);
router.get("/users/:handle/analytics",getanalytics);
module.exports=router;